import { useEffect, useState } from "react";
import { useParams, Link } from "react-router-dom";
import "../styles/PlayerProfile.css";

const PlayerProfile = () => {
  const { playerName } = useParams();
  const [player, setPlayer] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    fetch(`http://localhost:5000/api/players/${playerName}`)
      .then((response) => {
        if (!response.ok) {
          throw new Error("Player not found");
        }
        return response.json();
      })
      .then((data) => {
        setPlayer(data);
        setError(null);
      })
      .catch((error) => {
        console.error("Error fetching player:", error);
        setError(error.message);
      });
  }, [playerName]);

  if (error) return <div className="error">{error}</div>;
  if (!player) return <div className="loading">Loading Player Data...</div>;

  return (
    <div className="player-profile">
      <div className="profile-header">
        <img src={player.image} alt={player.name} className="profile-img" />
        <h1>{player.name}</h1>
        <h3>{player.role}</h3>

        {/* Official Profile Link */}
        <a href="https://www.chennaisuperkings.com/matchcentre/teamPage" target="_blank" rel="noopener noreferrer" className="profile-link">
          View Official Profile
        </a>

        {/* Official CSK Team Page Link */}
        <a
          href="https://www.chennaisuperkings.com/matchcentre/teamPage"
          target="_blank"
          rel="noopener noreferrer"
          className="profile-link csk-team-link"
        >
          Visit CSK Team Page
        </a>
      </div>

      <div className="stats">
        <h2>Player Stats</h2>
        <div className="stats-grid">
          <div className="stat-card">Matches: {player.stats.matches}</div>
          <div className="stat-card">Runs: {player.stats.runs}</div>
          <div className="stat-card">Wickets: {player.stats.wickets}</div>
          <div className="stat-card">Strike Rate: {player.stats.strikeRate}</div>
          <div className="stat-card">Economy: {player.stats.economy}</div>
          <div className="stat-card">Batting Avg: {player.stats.battingAverage}</div>
          <div className="stat-card">Bowling Avg: {player.stats.bowlingAverage}</div>
          <div className="stat-card">Highest Score: {player.stats.highestScore}</div>
          <div className="stat-card">Best Bowling: {player.stats.bestBowling}</div>
          <div className="stat-card">100s: {player.stats.hundreds}</div>
          <div className="stat-card">50s: {player.stats.fifties}</div>
          <div className="stat-card">4s: {player.stats.fours}</div>
          <div className="stat-card">6s: {player.stats.sixes}</div>
          <div className="stat-card">Overs: {player.stats.overs}</div>
          <div className="stat-card">Catches: {player.stats.catches}</div>
          <div className="stat-card">Stumpings: {player.stats.stumpings}</div>
        </div>

        {/* ChatGPT Stats Note */}
        <p className="stats-note">Player stats data is generated by ChatGPT.</p>
      </div>

      <Link to="/players" className="back-button">Back to Player Collection</Link>
    </div>
  );
};

export default PlayerProfile;
